#!/usr/bin/python3

"""Factorize digits into an outcome of two smaller digits"""
import sys
import time

def least_prime(n):
    """Find the smallest prime factor of n"""
    if n <= 1:
        return n
    if n % 2 == 0:
        return 2
    if n % 3 == 0:
        return 3
    if n % 5 == 0:
        return 5
    if n % 7 == 0:
        return 7

    # Skip multiples of 2, 3, 5, and 7
    for i in range(11, int(n**0.5) + 1, 2):
        if n % i == 0:
            return i
    return n

def factorize(digit):
    """Factorize a digit into two smaller digits"""
    if digit <= 1:
        return digit, 1

    elem = least_prime(digit)
    if elem == digit:
        return digit, 1

    fac = digit // elem
    return fac, elem

def factorize_file(path):
    """Factorize digits in the provided file into two smaller digits"""
    try:
        with open(path) as f:
            for line in f:
                n = int(line.strip())
                p, q = factorize(n)
                print(f"{n}={p}*{q}")

                if time.time() - start_time > 5:
                    print("Execution time exceeded the limit.")
                    break
    except FileNotFoundError:
        print(f"File '{path}' not found.")
    except ValueError:
        print("Invalid data in the file.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(f"Usage: {sys.argv[0]} <path>")

    factors = sys.argv[1]

    start_time = time.time()

    factorize_file(factors)
