#!/usr/bin/python3

"""Factorize digits into an outcome of two smaller digits"""
import sys
import time


PRIMES = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]

def least_prime(n):
    """Find the smallest prime factor of n"""
    if n < 2:
        return n

    for prime in PRIMES:
        if n % prime == 0:
            return prime

    candidate = PRIMES[-1] + 2
    while candidate * candidate <= n:
        if n % candidate == 0:
            return candidate
        candidate += 2 

    return n

def factorize(digit):
    """Factorize a digit into two smaller digits"""
    if digit <= 1:
        return digit, 1

    elem = least_prime(digit)
    if elem == digit:
        return digit, 1

    fac = digit // elem
    return fac, elem

def factorize_file(path):
    """Factorize digits in the provided file into two smaller digits"""
    try:
        with open(path) as f:
            for line in f:
                n = int(line.strip())
                p, q = factorize(n)
                print(f"{n}={p}*{q}")

                if time.time() - start_time > 5:
                    print("Execution time exceeded the limit.")
                    break
    except FileNotFoundError:
        print(f"File '{path}' not found.")
    except ValueError:
        print("Invalid data in the file.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(f"Usage: {sys.argv[0]} <path>")

    factors = sys.argv[1]

    start_time = time.time()

    factorize_file(factors)
