#!/usr/bin/python3

import sys
import time
import math

def prime_digit(num):
    """search if a digit is prime"""
    if num < 2:
        return False
    for k in range(2, int(math.sqrt(num)) + 1):
        if num % k == 0:
            return False
    return True

def trial_division(n):
    """Trial Division algorithm for factorizing a number"""
    if n < 2:
        return []

    factors = []
    # Divide by 2
    while n % 2 == 0:
        factors.append(2)
        n //= 2

    # Divide by odd numbers starting from 3
    for i in range(3, int(math.sqrt(n)) + 1, 2):
        while n % i == 0:
            factors.append(i)
            n //= i

    # If n is a prime number greater than 2
    if n > 2:
        factors.append(n)

    return factors

def factorize_file(path):
    """Factorizes digits in the provided file into prime factors"""
    try:
        with open(path) as f:
            n = int(f.read().strip())
            factors = trial_division(n)

            if len(factors) == 2 and prime_digit(factors[0]) and prime_digit(factors[1]):
                print(f"{n}={factors[0]}*{factors[1]}")
            else:
                print(f"Couldn't find two prime factors for {n}")
    except FileNotFoundError:
        print("File not found.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python rsa.py <filename>")
    else:
        start_time = time.time()
        factorize_file(sys.argv[1])
