#!/usr/bin/python3

import sys
import time
import math

def prime_digit(num):
    """search if a digit is prime"""
    if num < 2:
        return False
    for k in range(2, int(math.sqrt(num)) + 1):
        if num % k == 0:
            return False
    return True

def gcd(a, b):
    """search the largest divisor of a and b"""
    while b:
        a, b = b, a % b
    return a

def trial_division(n):
    """Trial division algorithm for factorizing a number"""
    factors = []
    i = 2
    while i * i <= n:
        if n % i:
            i += 1
        else:
            n //= i
            factors.append(i)
    if n > 1:
        factors.append(n)
    return factors

def factorize_file(path):
    """Factorizes digits in the provided file into two prime factors"""
    try:
        with open(path) as f:
            n = int(f.read().strip())
            factors = trial_division(n)
            if len(factors) == 2 and prime_digit(factors[0]) and prime_digit(factors[1]):
                print(f"{n}={factors[0]}*{factors[1]}")
            else:
                print(f"Couldn't find two prime factors for {n}")
    except FileNotFoundError:
        print("File not found.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python rsa.py <filename>")
    else:
        factorize_file(sys.argv[1])
